grails-app/domain/com/hrm/AttendanceDetails.groovy
package com.hrm


class AttendanceDetails {

    String description
    boolean present = false
    static belongsTo = [attendance: Attendance,userInfo: UserInfor]
    static constraints = {
        description nullable: true, blank: true
    }
    static mapping = {
        table 'attendance_details'
    }
}

grails-app/views/attendanceDetails/_form.gsp
<%@ page import="com.hrm.AttendanceDetails" %>






<g:if test="${attendanceDetailsInstance}">
  <div class="form-group ${hasErrors(bean: attendanceDetailsInstance, field: 'description', 'error')} ">
  <label class="control-label" for="description">
    <g:message code="attendanceDetails.description.label" default="Description"/>
    
  </label>
  <br>
  

<g:textField class="form-control" name="description" value="${attendanceDetailsInstance?.description}"/>



</g:if><g:else>
  <div class="form-group col-md-3">
   <label class="control-label" for="description">
  <g:message code="attendanceDetails.description.label" default="Description"/>
  
  </label>
  <br>
  <input class="form-control" name="description" value="${params.description}">
</g:else>  <div class="help-block"></div>
</div>



<g:if test="${attendanceDetailsInstance}">
  <div class="form-group ${hasErrors(bean: attendanceDetailsInstance, field: 'attendance', 'error')} required">
  <label class="control-label" for="attendance">
    <g:message code="attendanceDetails.attendance.label" default="Attendance"/>
    <span class="text-red">*</span>
  </label>
  <br>
  

<g:select class="form-control many-to-one" id="attendance" name="attendance.id" from="${com.hrm.Attendance.list()}" optionKey="id" required="" value="${attendanceDetailsInstance?.attendance?.id}"/>



</g:if><g:else>
  <div class="form-group col-md-3">
   <label class="control-label" for="attendance">
  <g:message code="attendanceDetails.attendance.label" default="Attendance"/>
  <span class="text-red">*</span>
  </label>
  <br>
  <input class="form-control" name="attendance" value="${params.attendance}">
</g:else>  <div class="help-block"></div>
</div>



<g:if test="${attendanceDetailsInstance}">
  <div class="form-group ${hasErrors(bean: attendanceDetailsInstance, field: 'present', 'error')} ">
  <label class="control-label" for="present">
    <g:message code="attendanceDetails.present.label" default="Present"/>
    
  </label>
  <br>
  

<g:checkBox name="present" value="${attendanceDetailsInstance?.present}" />



</g:if><g:else>
  <div class="form-group col-md-3">
   <label class="control-label" for="present">
  <g:message code="attendanceDetails.present.label" default="Present"/>
  
  </label>
  <br>
  <input class="form-control" name="present" value="${params.present}">
</g:else>  <div class="help-block"></div>
</div>



<g:if test="${attendanceDetailsInstance}">
  <div class="form-group ${hasErrors(bean: attendanceDetailsInstance, field: 'user', 'error')} required">
  <label class="control-label" for="user">
    <g:message code="attendanceDetails.user.label" default="User"/>
    <span class="text-red">*</span>
  </label>
  <br>
  

<g:select class="form-control many-to-one" id="user" name="user.id" from="${com.hrm.Users.list()}" optionKey="id" required="" value="${attendanceDetailsInstance?.user?.id}"/>



</g:if><g:else>
  <div class="form-group col-md-3">
   <label class="control-label" for="user">
  <g:message code="attendanceDetails.user.label" default="User"/>
  <span class="text-red">*</span>
  </label>
  <br>
  <input class="form-control" name="user" value="${params.user}">
</g:else>  <div class="help-block"></div>
</div>

grails-app/views/attendanceDetails/create.gsp
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="adminlte">
  <g:set var="entityName" value="${message(code: 'attendanceDetails.label', default: 'AttendanceDetails')}"/>
  <title><g:message code="default.create.label"
                    args="${[message( code: 'attendanceDetails.label', default:'attendanceDetails')]}">
  </g:message></title>

</head>

<body>
%{--<a href="#create-attendanceDetails" class="skip" tabindex="-1"><g:message code="default.link.skip.label"--}%
%{--                                                                                    default="Skip to content&hellip;"/></a>--}%

%{--<div class="nav" role="navigation">--}%
%{--  <ul>--}%
%{--    <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--}%
%{--    <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>--}%
%{--  </ul>--}%
%{--</div>--}%
<div class="attendanceDetails">
  <div id="create-attendanceDetails" class="content scaffold-create" role="main">
%{--    <h1><g:message code="default.create.label" args="[entityName]"/></h1>--}%
    <g:if test="${flash.message}">
      <div class="message alert alert-success" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${attendanceDetailsInstance}">
      <div class="alert alert-warning">
        <ul class="errors" role="alert">
          <g:eachError bean="${attendanceDetailsInstance}" var="error">
            <li<g:if
            test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
            error="${error}"/></li>
          </g:eachError>
        </ul>
      </div>
    </g:hasErrors>
    <div class="box box-primary">
      <div class="box-body">

        <g:form class="form rows"
            url="[resource: attendanceDetailsInstance, action: 'save']" >
    <g:render template="form"/>
    <div class="col-md-12"></div>

    <div class="buttons">
      <g:submitButton name="create" class="btn btn-success"
                      value="${message(code: 'default.button.create.label', default: 'Create')}"/>
    </div>
    </g:form>
      </div>

    </div>
</body>
</html>

grails-app/views/attendanceDetails/edit.gsp
<%@ page import="com.hrm.AttendanceDetails" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="adminlte">
  <g:set var="entityName" value="${message(code: 'attendanceDetails.label', default: 'AttendanceDetails')}"/>
  <title>
    <g:message code="default.edit.label"
               args="${[message( code: 'attendanceDetails.label', default:'attendanceDetails')]}">
    </g:message></title>

</head>

<body>
%{--		<a href="#edit-attendanceDetails" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>--}%
%{--		<div class="nav" role="navigation">--}%
%{--			<ul>--}%
%{--				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--}%
%{--				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>--}%
%{--				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>--}%
%{--			</ul>--}%
%{--		</div>--}%
<div class="attendanceDetails">
  <div id="edit-attendanceDetails" class="content scaffold-edit" role="main">
%{--    <h3><g:message code="default.edit.label" args="[entityName]"/></h3>--}%
    <g:if test="${flash.message}">
      <div class="message alert alert-success" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${attendanceDetailsInstance}">
      <div class="alert alert-warning">
      <ul class="errors" role="alert">
        <g:eachError bean="${attendanceDetailsInstance}" var="error">
          <li<g:if
               test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
            error="${error}"/></li>
        </g:eachError>
      </ul>
      </div>
    </g:hasErrors>
    <div class="box box-primary">
      <div class="box-body">
    <g:form class="form rows" url="[resource: attendanceDetailsInstance, action: 'update']"
            method="PUT" >
    <g:hiddenField class="form-control" name="version" value="${attendanceDetailsInstance?.version}"/>
    <g:render template="form"/>
    <div class="col-md-12"></div>
    <div class="buttons">
      <g:actionSubmit class="btn btn-success" action="update"
                      value="${message(code: 'default.button.update.label', default: 'Update')}"/>
    </div>
    </g:form>
      </div>
    </div>
  </div>
</div>
</body>
</html>

grails-app/views/attendanceDetails/index.gsp
<%@ page import="com.hrm.AttendanceDetails" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="adminlte">
  <g:set var="entityName" value="${message(code: 'attendanceDetails.label', default: 'AttendanceDetails')}"/>
  <title><g:message code="attendanceDetails.label"
                    args="${[message( code: 'attendanceDetails.label', default:'attendanceDetails')]}">
  </g:message></title>

</head>

<body>
<div class="attendanceDetails">

  <g:if test="${flash.message}">
    <div class="message" role="status">${flash.message}</div>
  </g:if>
  <div id="list-attendanceDetails" class="box box-primary" role="main">
    <div class="box-header">
      <h4 class="box-title collapsed" data-toggle="collapse" data-target="#search-box" aria-expanded="true"><i
        class="fa fa-search"></i><g:message code="default.search.label" args=" "/></h4>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool btn-search-toggle collapsed" data-toggle="collapse"
                data-target="#search-box" aria-expanded="true">
          <i class="fa fa-plus"></i>
        </button>
      </div>
      <div class="help-block"></div>

      <div class="search-attendanceDetails" id="search-box">
          <g:form class="form rows"
                  url="[resource: attendanceDetailsInstance, action: 'index']" >
          <g:render template="form"/>
          <div class="col-md-12"></div>
          <div class="buttons">
            <br>
            <g:submitButton name="search" class="btn btn-success"
                            value="${message(code: 'default.button.search.label', default: 'search')}"/>
          </div>
          </g:form>
        </div>
    </div>
    <div class="box-body">
      <div class="clearfix">
      </div>
      <g:link action="create" class="btn btn-success pull-right"><i class="fa fa-plus"></i></g:link>
      <table class="table table-hover" style="border-top: 1px solid #f4f4f4; border-bottom: 1px solid #f4f4f4">
        <thead>
        <tr>
          <th>#</th>
          
          <g:sortableColumn property="description"
                            title="${message(code: 'attendanceDetails.description.label', default: 'Description')}"/>
          
          <th><g:message code="attendanceDetails.attendance.label" default="Attendance"/></th>
          
          <g:sortableColumn property="present"
                            title="${message(code: 'attendanceDetails.present.label', default: 'Present')}"/>
          
          <th><g:message code="attendanceDetails.user.label" default="User"/></th>
          
          <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <g:each in="${attendanceDetailsInstanceList}" status="i" var="attendanceDetailsInstance">
          <tr class="${(i % 2) == 0 ? 'even' : 'odd'}" scope="col">
            
            <td>1</td>
            <td><g:link action="show" id="${attendanceDetailsInstance.id}">${fieldValue(bean: attendanceDetailsInstance, field: "description")}</g:link></td>
            
            <td>${fieldValue(bean: attendanceDetailsInstance, field: "attendance")}</td>
            
            <td><g:formatBoolean boolean="${attendanceDetailsInstance.present}"/></td>
            
            <td>${fieldValue(bean: attendanceDetailsInstance, field: "user")}</td>
            
            <td><g:link action="edit" resource="${attendanceDetailsInstance}"><i
              class="glyphicon glyphicon-pencil"></i></g:link><g:link class="delete" action="delete"
                                                                      resource="${attendanceDetailsInstance}"><i
                class="glyphicon glyphicon-remove"></i></g:link></td>
          </tr>
        </g:each>
        </tbody>
      </table>
    </div>
    <div class="box-footer">
      <div class="pagination sang-pagination">
        <g:paginate total="${attendanceDetailsInstanceCount ?: 0}"/>
      </div>
    </div>
  </div>
</div>
</body>
</html>

grails-app/views/attendanceDetails/show.gsp
<%@ page import="com.hrm.AttendanceDetails" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="adminlte">
  <g:set var="entityName" value="${message(code: 'attendanceDetails.label', default: 'AttendanceDetails')}"/>
  <title><g:message code="default.show.label"
                    args="${[message( code: 'attendanceDetails.label', default:'attendanceDetails')]}">
</g:message></title>
  <style>

  </style>
</head>

<body>
%{--		<a href="#show-attendanceDetails" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>--}%
%{--		<div class="nav" role="navigation">--}%
%{--			<ul>--}%
%{--				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--}%
%{--				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>--}%
%{--				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>--}%
%{--			</ul>--}%
%{--		</div>--}%
<div class="attendanceDetails">
  <div id="show-attendanceDetails" class="content scaffold-show" role="main">
%{--    <h3><g:message code="default.show.label" args="[entityName]"/></h3>--}%
    <g:if test="${flash.message}">
      <div class="message alert alert-success" role="status">${flash.message}</div>
    </g:if>
    <div class="box box-primary">
      <div class="box-body">
        <h4><i class="fa fa-book"></i>Details: </h4>
        <table class="attendanceDetails table no-margin"s>
          
          %{--          <g:if test="${attendanceDetailsInstance?.description}">--}%
          <tr class="fieldcontain">
            <th id="description-label" class="property-label"><g:message
              code="attendanceDetails.description.label" default="Description"/></th>
            
            <td class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${attendanceDetailsInstance}"
                                                                                       field="description"/></td>
            
          </tr>
          %{--          </g:if>--}%
          
          %{--          <g:if test="${attendanceDetailsInstance?.attendance}">--}%
          <tr class="fieldcontain">
            <th id="attendance-label" class="property-label"><g:message
              code="attendanceDetails.attendance.label" default="Attendance"/></th>
            
            <td class="property-value" aria-labelledby="attendance-label"><g:link
              controller="attendance" action="show"
              id="${attendanceDetailsInstance?.attendance?.id}">${attendanceDetailsInstance?.attendance?.encodeAsHTML()}</g:link></td>
            
          </tr>
          %{--          </g:if>--}%
          
          %{--          <g:if test="${attendanceDetailsInstance?.present}">--}%
          <tr class="fieldcontain">
            <th id="present-label" class="property-label"><g:message
              code="attendanceDetails.present.label" default="Present"/></th>
            
            <td class="property-value" aria-labelledby="present-label"><g:formatBoolean
              boolean="${attendanceDetailsInstance?.present}"/></td>
            
          </tr>
          %{--          </g:if>--}%
          
          %{--          <g:if test="${attendanceDetailsInstance?.user}">--}%
          <tr class="fieldcontain">
            <th id="user-label" class="property-label"><g:message
              code="attendanceDetails.user.label" default="User"/></th>
            
            <td class="property-value" aria-labelledby="user-label"><g:link
              controller="users" action="show"
              id="${attendanceDetailsInstance?.user?.id}">${attendanceDetailsInstance?.user?.encodeAsHTML()}</g:link></td>
            
          </tr>
          %{--          </g:if>--}%
          
        </table>
        <g:form url="[resource: attendanceDetailsInstance, action: 'delete']" method="DELETE">
          <fieldset class="buttons">
            <g:link class="edit btn btn-info" action="edit" resource="${attendanceDetailsInstance}"><g:message
              code="default.button.edit.label"
              default="Edit"/></g:link>
            <g:actionSubmit class="delete btn btn-danger" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
          </fieldset>
        </g:form>
      </div>
    </div>
  </div>
</div>
</body>
</html>