grails-app/domain/com/hrm/UserInfor.groovy
package com.hrm

class UserInfor {
  String name
  boolean gender
  Date dateOfBirth
  String email
  String phoneNumber
  String permanentAddress
  String homeAddress
  String photo
  String personalId
  String personalIdPhotoA
  Date releaseDate
  String releaseIn
  String certificate
  String certificatePhoto
  String status
  String level
  float entranceSalary
  int dependant = 0
  static belongsTo = [laborContract: LaborContract, permanentWard: Ward, permanentDistrict: District, permanentProvince: Province,
                      homeWard     : Ward, homeDistrict: District, homeProvince: Province]
  static constraints = {
    name nullable: false, blank: false, name:true , matches: '[a-zA-Z]{1,9}(\\s[a-zA-Z]{2,9}){0,4}\\s[a-zA-Z]{1,8}+'
    email nullable: false, blank: false, email: true, matches: '^([a-zA-Z0-9_\\.\\-])+\\@(([a-zA-Z0-9\\-])+\\.)+([a-zA-Z0-9]{2,4})+$'
    dateOfBirth nullable: false, blank: false
    phoneNumber nullable: false, blank: false, matches: '[0-9]{10,11}'
    dependant min: 0, max: 10
    photo nullable: true,blank: true
    personalIdPhotoA nullable: true,blank: true
    certificatePhoto nullable: true,blank: true

  }
  static mapping = {
    table 'user_info'
  }
}

grails-app/controllers/com/hrm/UserInforController.groovy
package com.hrm

import com.hrm.common.CommonUtils
import grails.plugin.springsecurity.annotation.Secured
import grails.plugin.springsecurity.authentication.encoding.BCryptPasswordEncoder
import org.springframework.core.io.ByteArrayResource
import org.springframework.security.crypto.password.PasswordEncoder

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
@Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
class UserInforController {

  static allowedMethods = [save: "POST", update: "POST", delete: "DELETE"]
  UserInforService userInforService
  def assetResourceLocator
  def springSecurityService

  @Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])

  def index(Integer max) {
    params.max = Math.min(max ?: 10, 100)
    params.offset = params.offset ? params.offset as Integer : 0;
    def listUserInstance = UserInfor.list(params);
    if (params.search != null) {
      listUserInstance = userInforService.find(params)
    }
    def listDepartInstance = [:]
    DepartUser.findAllByUserInfoInList(listUserInstance)?.each { departUser ->
      listDepartInstance[departUser.userInfo.id] = departUser.depart;
    }
    respond listUserInstance, model: [userInforInstanceCount: UserInfor.count(), 'params': params, mapDepartInstance: listDepartInstance]
  }

  @Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
  def show(UserInfor userInforInstance) {
    respond userInforInstance
  }

  @Secured(['ROLE_USER','ROLE_ADMIN','ROLE_MANAGER','ROLE_SUPERVISOR'])
  def profile(UserInfor userInforInstance) {
    def model = [:]
    def listRequestInstance = Requests.findAllByStaffAndStatus(userInforInstance, 'ACCEPTED')
    def departInstance = DepartUser.findByUserInfo(userInforInstance);
    model['listRequestInstance'] = listRequestInstance;
    if (departInstance) {
      def roomMaster = DepartUser.findByDepartAndIs_room_master(departInstance.depart, true).userInfo
      model['departInstance'] = departInstance.depart;
      model['roomMaster'] = roomMaster;
    }
    int restRemainDays = userInforService.getRestDaysRemain(userInforInstance);
    model['remainDays'] = 12 - restRemainDays;
    respond userInforInstance, model: model
  }

  @Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
  def create() {
    respond new UserInfor(params), model: ['userDepartInstance': new Depart()]
  }

  @Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
  @Transactional
  def save() {
    def tempUserInforInstance = new UserInfor();
    tempUserInforInstance = userInforService.loadUserInforInstance(params, tempUserInforInstance)
    if (tempUserInforInstance == null) {
      notFound()
      return
    }

    if (tempUserInforInstance.hasErrors()) {
      respond tempUserInforInstance.errors, view: 'create'
      return
    }
    userInforService.saveUserImage(params.image_photo, '');
    userInforService.saveUserImage(params.image_certificate, '');
    userInforService.saveUserImage(params.image_personal_id, '');

    if (tempUserInforInstance.save(flush: true)) {
      if (params.depart != "0" && params.depart != null) {
        def tempDepartUserInstance = new DepartUser();
        tempDepartUserInstance.setIs_leader(false);
        tempDepartUserInstance.setIs_room_master(false);
        tempDepartUserInstance.setDepart(Depart.findById(Long.parseLong(params.depart + "")))
        tempDepartUserInstance.setUserInfo(tempUserInforInstance)
        tempDepartUserInstance.save(flush: true);
      }
    } else {
      flash.message = 'Create failed'
      respond tempUserInforInstance, view: 'create'
      return
    }
//
//    def userInforInstance = UserInfor.findByNameAndEmailAndGenderAndDateOfBirthAndCertificate(
//      tempUserInforInstance.name, tempUserInforInstance.email, tempUserInforInstance.gender, tempUserInforInstance.dateOfBirth, tempUserInforInstance.certificate)

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.created.message', args: [message(code: 'userInfor.label', default: 'UserInfor'), tempUserInforInstance.name])
        redirect tempUserInforInstance
      }
      '*' { respond tempUserInforInstance, [status: CREATED] }
    }
  }

  @Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
  def edit(UserInfor userInforInstance) {
    def userDepartInstance
    def currentDepartUser = DepartUser.findByUserInfo(userInforInstance)
    if (currentDepartUser) {
      userDepartInstance = Depart.findById(currentDepartUser.depart.id)
    } else {
      userDepartInstance = new Depart()
    }
    respond userInforInstance, model: ['userDepartInstance': userDepartInstance]
  }

  @Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
  @Transactional
  def update() {
    println "params ==============> " + params
    def userInforInstance = UserInfor.findById(Long.parseLong(params.id));
    if (userInforInstance == null) {
      notFound()
      return
    }
    userInforInstance = userInforService.loadUserInforInstance(params, userInforInstance)
    if (userInforInstance.hasErrors()) {
      respond userInforInstance.errors, view: 'create'
      return
    }

    userInforInstance.save(flush: true)
    def departUserInstance = DepartUser.findAllByUserInfo(userInforInstance)
    departUserInstance?.each { depart ->
      depart.delete()
    }
    if (params.image_photo) {
      userInforService.saveUserImage(params.image_photo, '');
    }
    if (params.image_certificate) {
      userInforService.saveUserImage(params.image_certificate, '');
    }
    if (params.image_personal_id) {
      userInforService.saveUserImage(params.image_personal_id, '');
    }

    if (params.depart != "0" && params.depart != null) {
      println "======================== SAVE DEPART ================= "


      def tempDepartUserInstance = new DepartUser();
      tempDepartUserInstance.setVersion(0)
      tempDepartUserInstance.setIs_leader(false);
      tempDepartUserInstance.setIs_room_master(false);
      tempDepartUserInstance.setDepart(Depart.findById(Long.parseLong(params.depart + "")))
      tempDepartUserInstance.setUserInfo(userInforInstance)
      tempDepartUserInstance.save(flush: true)

    }
    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.updated.message', args: [message(code: 'UserInfor.label', default: 'UserInfor'), userInforInstance.id])
        redirect userInforInstance
      }
      '*' { respond userInforInstance, [status: OK] }
    }
  }

  @Secured(['ROLE_USER','ROLE_ADMIN','ROLE_MANAGER','ROLE_SUPERVISOR'])
  @Transactional
  def changePass() {
    String currentPassword = params.current_password
    String newPassword = params.new_password
    String confirmPassword = params.confirm_password
    String id = params.id
    def currentUser = springSecurityService.getCurrentUser();
    if (currentUser) {
      PasswordEncoder encoder = new org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder();
      if (encoder.matches(currentPassword, currentUser.getPassword())) {
        if (newPassword.toString().matches(confirmPassword.toString())) {
          def user = Users.findById(currentUser.id);
          user.setPassword(newPassword)
          user.save(flush: true)
          flash.message = 'Password has been changed'
          flash.message_type = 'success'
        } else {
          flash.message = 'Confirm password is not matches'
          flash.message_type = 'warning'
        }
      } else {
        flash.message = 'Current password is not matches.'
        flash.message_type = 'warning'
      }
    } else {
      flash.message = 'Something was wrong.'
      flash.message_type = 'warning'
    }

    redirect action: 'profile', id: id
  }

  @Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
  @Transactional
  def delete(UserInfor userInforInstance) {

    if (userInforInstance == null) {
      notFound()
      return
    }
    def departInstance = DepartUser.findAllByUserInfo(userInforInstance)
    departInstance.each { departUser ->
      departUser.delete()
    }
    userInforInstance.delete flush: true
    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.deleted.message', args: [message(code: 'UserInfor.label', default: 'UserInfor'), userInforInstance.id])
        redirect action: "index", method: "GET"
      }
      '*' { render status: NO_CONTENT }
    }
  }

  @Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
  def generateUserInfo() {
    def laborContractInstance = LaborContract.findById(Long.parseLong(params.id))
    def userInforInstance = new UserInfor()
    userInforInstance.name = laborContractInstance.employeeName
    userInforInstance.dateOfBirth = laborContractInstance.employeeDateOfBirth
    userInforInstance.phoneNumber = laborContractInstance.employeePhoneNumber
    userInforInstance.laborContract = laborContractInstance
    respond userInforInstance, view: 'create', model: ['userDepartInstance': new Depart()]
  }

  @Secured(['ROLE_USER','ROLE_ADMIN','ROLE_MANAGER','ROLE_SUPERVISOR'])
  def loadImage() {
    File tempFile = null;
    println("============== Streamming file ==============")
    println('params ========> ' + params)
    response.setContentType("image/**")
    if (params.path) {
      String path = CommonUtils.IMAGES_PATH + '/' + params.path
      tempFile = new File(path)
      if (tempFile.exists()) {
        response.setHeader("Content-disposition", "filename=${CommonUtils.IMAGES_PATH + '/' + path}")
        response.outputStream << tempFile.newInputStream()
      } else {
        ByteArrayResource resource = assetResourceLocator.findAssetForURI('default.jpg')
        response.outputStream << resource.inputStream
      }
    } else {
      ByteArrayResource resource = assetResourceLocator.findAssetForURI('default.jpg')
      response.outputStream << resource.inputStream
    }

    println("============== End function ==============")
  }

  @Secured(['ROLE_USER','ROLE_ADMIN','ROLE_MANAGER','ROLE_SUPERVISOR'])
  def uploadImage() {

grails-app/views/userInfor/_change-pass.gsp
<div class="box-body">
  <g:form method="post" class="form rows" url="[resource: userInforInstance, action: 'changePass']">
    <div class="form-group">
      <label>Current Password</label>
      <input class="form-control" name="current_password" type="password" required>
    </div>

    <div class="form-group">
      <label>New Password</label>
      <input class="form-control" name="new_password" type="password" required>
    </div>

    <div class="form-group">
      <label>Confirm Password</label>
      <input class="form-control" name="confirm_password" type="password" required>
    </div>
    <input class="form-control" name="id" type="hidden" value="${userInforInstance.id}">
    <div class="form-group">
      <button class="btn btn-primary" type="submit">Submit</button>
    </div>
  </g:form>
</div>

grails-app/views/userInfor/_my-requests.gsp
<div class=" table-responsive no-padding">
  <div class="col-md-2 pull-right">
    <g:link class="btn btn-success" controller="requests" action="create" params="['userId':userInforInstance?.id,'departId':departInstance?.id]">New request</g:link>
  </div>
  <g:if test="${listRequestInstance}">
    <table class="table table-hover">
      <thead>
      <tr>
        %{--      <th>#</th>--}%
        %{--      <th>User</th>--}%
        %{--      <th>Date</th>--}%
        %{--      <th>Status</th>--}%
        %{--      <th>Reason</th>--}%
        <th></th>
        <th>Status</th>
        <th></th>
        <th>Content</th>
        <th>Accepted At</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <g:each in="${listRequestInstance}" var="request">

        <tr >
          <td style="vertical-align: middle" width="100px"> <img width="80" height="80" src="${createLink(controller: 'userInfor', action: 'loadImage',
            params: [
              'image': true,
              'path' : request?.staff?.photo])}" class="img-circle"/></td>
          <td style="vertical-align: middle" width="100px"><i class="fa  fa-long-arrow-right" style="font-size: 80px; color: #b2b2b2"></i><br><span class="label label-success">Accepted</span></td>
          <td style="vertical-align: middle" width="100px"><img width="80" height="80" src="${createLink(controller: 'userInfor', action: 'loadImage',
            params: [
              'image': true,
              'path' : roomMaster?.photo])}" class="img-circle"/></td>
          <td style="vertical-align: middle" width="200px">${ request?.type?.description}</td>
          <td style="vertical-align: middle"><g:formatDate format="yyyy-MM-dd" date="${request?.acceptedAt}"></g:formatDate> </td>
          <td style="vertical-align: middle"></td>
          <td style="vertical-align: middle"></td>
          <td style="vertical-align: middle"></td>
        </tr>
      </g:each>
      </tbody>
    </table>
  </g:if><g:else>
  We have no avaiable request !!
</g:else>
</div>

grails-app/views/userInfor/_profile-aside.gsp
<%@ page import="com.hrm.UserInforService" %>
<!-- Profile Image -->
<div class="box box-primary">
  <div class="box-body box-profile">
    <img class="profile-user-img img-responsive img-circle"
         src="${userInforInstance.photo ? createLink(controller: 'userInfor', action: 'loadImage',
           params: [
             'image': userInforInstance ? true : false,
             'path' : userInforInstance?.photo]) : resource(dir: 'asset/dist/img', file: 'no-image.png')}"
         alt="User profile picture">

    <h3 class="profile-username text-center">${userInforInstance.name}</h3>

    <p class="text-muted text-center">${userInforInstance.laborContract.profession.professionName}</p>

    <ul class="list-group list-group-unbordered">
      <li class="list-group-item">
        <b>Date Of Birth</b> <a class="pull-right"><g:formatDate format="yyyy-MM-dd"
                                                                 date="${userInforInstance.dateOfBirth}"/></a>
      </li>
      <li class="list-group-item">
        <b>Phone Number</b> <a class="pull-right">${userInforInstance.phoneNumber}</a>
      </li>
      <%
        def departUser = com.hrm.DepartUser.findByUserInfo(userInforInstance)
        def departInstance
        if (departUser) {
          departInstance = com.hrm.Depart.findById(departUser.depart.id).name

        } else {
          departInstance = ''
        }
      %>
      <li class="list-group-item">
        <b>Depart</b> <a
        class="pull-right">${departInstance}</a>
      </li>
      <%    %>
      <li class="list-group-item">
        <b>Rest days remain</b> <a
        class="pull-right">${remainDays}/12</a>
      </li>
    </ul>
    %{--        <a href="#" class="btn btn-primary btn-block"><b>Follow</b></a>--}%
  </div>
  <!-- /.box-body -->
</div>

<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">About Me</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <strong><i class="fa fa-book margin-r-5"></i> Level</strong>

    <p class="text-muted">
      ${userInforInstance.level}
    </p>
    <hr>

    <strong><i class="fa fa-map-marker margin-r-5"></i> Location</strong>

    <p
      class="text-muted">${userInforInstance.permanentAddress} ${userInforInstance.permanentWard.name} ${userInforInstance.permanentDistrict.name} ${userInforInstance.permanentProvince.name}</p>
    %{--        <hr>--}%

    %{--        <strong><i class="fa fa-pencil margin-r-5"></i> Skills</strong>--}%

    %{--        <p>--}%
    %{--          <span class="label label-danger">UI Design</span>--}%
    %{--          <span class="label label-success">Coding</span>--}%
    %{--          <span class="label label-info">Javascript</span>--}%
    %{--          <span class="label label-warning">PHP</span>--}%
    %{--          <span class="label label-primary">Node.js</span>--}%
    %{--        </p>--}%
    <hr>
    <strong><i class="fa fa-file-text-o margin-r-5"></i> Notes</strong>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
  </div>
  <!-- /.box-body -->
</div>

grails-app/views/userInfor/create.gsp
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="adminlte">
  <g:set var="entityName" value="${message(code: 'userInfor.label', default: 'UserInfor')}"/>
  <title><g:message code="default.create.label"
                    args="${[message(code: 'userInfor.label', default: 'userInfor')]}">
  </g:message></title>

</head>
<body>

<div class="userInfor">
  <div id="create-userInfor" class="content scaffold-create" role="main">
  %{--    <h1><g:message code="default.create.label" args="[entityName]"/></h1>--}%
    <g:if test="${flash.message}">
      <div class="message alert alert-success" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${userInforInstance}">
      <div class="alert alert-warning">
        <ul class="errors" role="alert">
          <g:eachError bean="${userInforInstance}" var="error">
            <li<g:if
            test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
            error="${error}"/></li>
          </g:eachError>
        </ul>
      </div>
    </g:hasErrors>
    <div class="box box-primary">
      <div class="box-body">
        <g:form class="form"
                url="[resource: userInforInstance, action: 'save']"
                enctype="multipart/form-data">
          <div class="row">
            <g:render template="form"/>

            <div class="col-md-12"></div>
            <div class="col-md-12">
              <div class="col-md-3">
                <g:submitButton name="create" class="btn btn-success"
                                value="${message(code: 'default.button.create.label', default: 'Create')}"/>
              </div>
            </div>
          </div>
        </g:form>
      </div>

    </div>
  </div>

</div>
</body>
</html>

grails-app/views/userInfor/edit.gsp
<%@ page import="com.hrm.UserInfor" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="adminlte">
  <g:set var="entityName" value="${message(code: 'userInfor.label', default: 'UserInfor')}"/>
  <title>
    <g:message code="default.edit.label"
               args="${[message(code: 'userInfor.label', default: 'userInfor')]}">
    </g:message></title>

</head>

<body>

<div class="userInfor">
  <div id="edit-userInfor" class="content scaffold-edit" role="main">
      <h3><g:message code="default.edit.label" args="[entityName]"/></h3>
    <g:if test="${flash.message}">
      <div class="message alert alert-success" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${userInforInstance}">
      <div class="alert alert-warning">
        <ul class="errors" role="alert">
          <g:eachError bean="${userInforInstance}" var="error">
            <li<g:if
            test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
          </g:eachError>
        </ul>
      </div>
    </g:hasErrors>
    <div class="box box-primary">
      <div class="box-body">
        <g:form class="form rows" url="[resource: userInforInstance, action: 'update']"
                enctype="multipart/form-data" method="POST">
          <g:hiddenField class="form-control" name="version" value="${userInforInstance?.version}"/>
          <g:render template="form"/>
          <div class="col-md-12"></div>

          <div class="col-md-3">
            <div class="col-md-3">
              <g:actionSubmit class="btn btn-success" action="update"
                              value="${message(code: 'default.button.update.label', default: 'Update')}"/>
            </div>
          </div>
        </g:form>
      </div>
    </div>
  </div>
</div>
</body>
</html>

grails-app/views/userInfor/index.gsp
<%@ page import="com.hrm.DepartUser; com.hrm.UserInfor" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="adminlte">
  <g:set var="entityName" value="${message(code: 'userInfor.label', default: 'UserInfor')}"/>
  <title><g:message code="userInfor.label"
                    args="${[message(code: 'userInfor.label', default: 'userInfor')]}">
  </g:message></title>
<style>
td {
  text-align: left;
}

</style>
</head>

<body>
<div class="userInfor">

  <g:if test="${flash.message}">
    <div class="alert alert-success" role="alert">${flash.message}</div>
  </g:if>
  <div id="list-userInfor" class="box box-primary" role="main">
    <div class="box-header">
      <h4 class="box-title collapsed" data-toggle="collapse" data-target="#search-box" aria-expanded="true"><i
        class="fa fa-search"></i><g:message code="default.search.label" args=" "/></h4>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool btn-search-toggle collapsed" data-toggle="collapse"
                data-target="#search-box" aria-expanded="true">
          <i class="fa fa-plus"></i>
        </button>
      </div>

      <div class="help-block"></div>

      <div class="search-userInfor" id="search-box">
        <g:form class="form rows"
                url="[resource: userInforInstance, action: 'index']">
          <g:render template="form"/>
          <div class="col-md-3">
            <g:submitButton name="search" class="btn btn-success"
                            value="${message(code: 'default.button.search.label', default: 'search')}"/>
          </div>
        </g:form>
      </div>
    </div>

    <div class="box-body">
      <div class="clearfix">
      </div>
      <g:link action="create" class="btn btn-success pull-right"><i class="fa fa-plus"></i></g:link>
      <table class="table table-hover" style="border-top: 1px solid #f4f4f4; border-bottom: 1px solid #f4f4f4">
        <thead>
        <tr>
          <th>#</th>

          <g:sortableColumn property="name" style="text-align: left;"
                            title="${message(code: 'userInfor.name.label', default: 'Name')}"  />

          <g:sortableColumn property="email" style="text-align: left;"
                            title="${message(code: 'userInfor.email.label', default: 'Email')}"/>

          <g:sortableColumn property="dateOfBirth"
                            title="${message(code: 'userInfor.dateOfBirth.label', default: 'Date Of Birth')}"/>

          <g:sortableColumn property="phoneNumber"
                            title="${message(code: 'userInfor.phoneNumber.label', default: 'Phone Number')}"/>

          <g:sortableColumn property="certificate"
                            title="${message(code: 'userInfor.certificate.label', default: 'Certificate')}"/>

          <th>Depart</th>
          <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <g:each in="${userInforInstanceList}" status="i" var="userInforInstance">
          <tr class="${(i % 2) == 0 ? 'even' : 'odd'}" scope="col">

            <td>${i+1}</td>
            <td style="text-align: left"><g:link action="show"
                        id="${userInforInstance.id}">${fieldValue(bean: userInforInstance, field: "name")}</g:link></td>

            <td style="text-align: left">${fieldValue(bean: userInforInstance, field: "email")}</td>

            <td ><g:formatDate format="yyyy-MM-dd" date="${userInforInstance.dateOfBirth}"/></td>

            <td >${fieldValue(bean: userInforInstance, field: "phoneNumber")}</td>

            <td >${fieldValue(bean: userInforInstance, field: "certificate")}</td>

            <td >${mapDepartInstance[userInforInstance.id]?.name}</td>
            <td ><g:link action="edit" resource="${userInforInstance}"><i
              class="glyphicon glyphicon-pencil"></i></g:link><g:link class="delete" action="delete"
                                                                      resource="${userInforInstance}"><i
                class="glyphicon glyphicon-remove"></i></g:link></td>
          </tr>
        </g:each>
        </tbody>
      </table>
    </div>

    <div class="box-footer">
      <div class="pagination sang-pagination">
        <g:paginate total="${userInforInstanceCount ?: 0}"/>
      </div>
    </div>
  </div>
</div>
</body>
</html>

grails-app/views/userInfor/profile.gsp
<%--
  Created by IntelliJ IDEA.
  User: nhm95
  Date: 3/23/2020
  Time: 3:26 PM
--%>
<%@ page import="com.hrm.UserInforService; com.hrm.DepartUser; com.hrm.UserInfor" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
  <meta name="layout" content="adminlte">
  <g:set var="entityName" value="${message(code: 'userInfor.label', default: 'UserInfor')}"/>
  <title><g:message code="userInfor.label"
                    args="${[message(code: 'userInfor.label.profile', default: 'User Profile')]}">
  </g:message></title>

</head>

<body>
<g:if test="${flash.message}">
  <div class="message alert alert-${flash.message_type}" role="status">${flash.message}</div>
</g:if>
<div class="row">

  <div class="col-md-3">
    <g:render template="profile-aside"></g:render>
    <!-- /.box -->
  </div>
  <!-- /.col -->
  <div class="col-md-9">
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs">
        %{--        <li ><a href="#general" data-toggle="tab">General</a></li>--}%
        %{--        <li><a href="#contract" data-toggle="tab">Contract</a></li>--}%
        %{--        <li><a href="#timeline" data-toggle="tab">Work</a></li>--}%
        <li class="active"><a href="#request" data-toggle="tab">Request</a></li>
        <li><a href="#changePass" data-toggle="tab">Change Password</a></li>
      </ul>

      <div class="tab-content">
        %{--        <div class="tab-pane" id="general">--}%
        %{--          <!-- The timeline -->--}%
        %{--          <g:render template="general"></g:render>--}%
        %{--        </div>--}%
        %{--        <div class="active tab-pane" id="contract">--}%
        %{--          <!-- Post -->--}%
        %{--          <!-- /.post -->--}%
        %{--        </div>--}%
        %{--        <!-- /.tab-pane -->--}%
        %{--        <div class="tab-pane" id="timeline">--}%
        %{--          <!-- The timeline -->--}%
        %{--        </div>--}%
        <!-- /.tab-pane -->

        <div class="tab-pane active" id="request">
          <g:render template="my-requests"></g:render>
        </div>

        <div class="tab-pane" id="changePass">
          <g:render template="change-pass"></g:render>
        </div>
        <!-- /.tab-pane -->
      </div>
      <!-- /.tab-content -->
    </div>
    <!-- /.nav-tabs-custom -->
  </div>
  <!-- /.col -->
</div>
</body>
</html>