grails-app/domain/com/hrm/LaborContract.groovy
package com.hrm
import java.sql.Date

class LaborContract {

    String contractNumber
    String employeeName
    String employerName
    Date employerDateOfBirth = new Date(new java.util.Date().getTime())
    Date employeeDateOfBirth = new Date(new java.util.Date().getTime())
    String employerPhoneNumber
    String employeePhoneNumber
    String content
    String photo
    String fileFolder
    Date createdDate = new Date(new java.util.Date().getTime())
    Date signDate = new Date(new java.util.Date().getTime())
    Date effectiveDate = new Date(new java.util.Date().getTime())
    Date expiredDate = new Date(new java.util.Date().getTime())

    static belongsTo = [type:TypesOfContract, profession:Profession] // position
    static constraints = {
        contractNumber unique: true
    }
    static mapping = {
    }
}

grails-app/controllers/com/hrm/LaborContractController.groovy
package com.hrm

import com.hrm.common.CommonUtils
import grails.plugin.springsecurity.annotation.Secured
import org.springframework.core.io.ByteArrayResource

import java.sql.Date
import java.sql.Timestamp
import java.text.SimpleDateFormat

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
@Transactional(readOnly = true)
class LaborContractController {
  /* ***************************************************
     *              READ COMMAND FIRST   // Ngoc Anh   *
     ***************************************************/

  static allowedMethods = [save: "POST", edit: 'GET', delete: "DELETE"]
  LaborContractService laborContractService
  def assetResourceLocator

  @Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
  def index(Integer max) {
    params.max = Math.min(max ?: 10, 100)
    params.offset = params.offset ? params.offset : 0
    params.firstResult = params.offset * params.max
    def listLaborContractInstance = LaborContract.list(params)
    if (params.search != null) {
      listLaborContractInstance = laborContractService.find(params)
    }
    respond listLaborContractInstance, model: [laborContractInstanceCount: LaborContract.count(), 'params': params]
  }

  @Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
  def show(LaborContract laborContractInstance) {
    respond laborContractInstance
  }

  @Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
  def create() {
    respond new LaborContract(params)
  }

  @Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
  @Transactional
  def save(LaborContract laborContractInstance) {
    if (laborContractInstance == null) {
      notFound()
      return
    }
    SimpleDateFormat format = new SimpleDateFormat('yyyy-MM-dd')
    laborContractInstance.setCreatedDate(new Date(new java.util.Date().getTime()))
    def tempLaborInstance = new LaborContract()

    tempLaborInstance.setEffectiveDate(new Date(format.parse(params.effectiveDate).getTime()))
    tempLaborInstance.setExpiredDate(new Date(format.parse(params.expiredDate).getTime()))
    tempLaborInstance.setSignDate(new Date(format.parse(params.signDate).getTime()))
    tempLaborInstance.setContractNumber(laborContractInstance.contractNumber)
    tempLaborInstance.setContent(laborContractInstance.content)

    tempLaborInstance.setEmployeeName(laborContractInstance.employeeName)
    tempLaborInstance.setEmployeeDateOfBirth(new Date(format.parse(params.employeeDateOfBirth).getTime()))
    tempLaborInstance.setEmployeePhoneNumber(laborContractInstance.employeePhoneNumber)

    tempLaborInstance.setEmployerName(laborContractInstance.employerName)
    tempLaborInstance.setEmployerDateOfBirth(new Date(format.parse(params.employerDateOfBirth).getTime()))
    tempLaborInstance.setEmployerPhoneNumber(laborContractInstance.employerPhoneNumber)

    tempLaborInstance.setProfession(laborContractInstance.profession)
    tempLaborInstance.setType(laborContractInstance.type)

    tempLaborInstance.setPhoto(params.photo)
    tempLaborInstance.setFileFolder(params.fileFolder)

    if (tempLaborInstance.hasErrors()) {
      respond tempLaborInstance.errors, view: 'create'
      return
    }
    laborContractService.saveContractImage(params.image_photo, '');
    laborContractService.saveContractFile(params.attachFile, '');
    if (laborContractInstance.save(flush: true)) {
    } else {
      flash.message = 'Create failed'
      respond laborContractInstance, view: 'create'
      return
    }
    // tempLaborInstance.save flush:true

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.created.message', args: [message(code: 'laborContract.label', default: 'LaborContract'), tempLaborInstance.id])
        redirect tempLaborInstance
      }
      '*' { respond tempLaborInstance, [status: CREATED] }
    }
  }

  @Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
  def edit(LaborContract laborContractInstance) {
    respond laborContractInstance
  }

  @Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
  @Transactional
  def update(LaborContract laborContractInstance) {
    if (laborContractInstance == null) {
      notFound()
      return
    }
    SimpleDateFormat format = new SimpleDateFormat('yyyy-MM-dd hh:mm:ss')
    println "class 1: " + laborContractInstance.effectiveDate.class

    def tempLaborInstance = laborContractInstance
    println "class 2: " + format.parse(params.effectiveDate + " 00:00:00.0").class
    println "class 3: " + new Date(format.parse(params.effectiveDate + " 00:00:00.0").getTime()).class + "\n"
    println "date 1: " + laborContractInstance.effectiveDate
    println "date 2: " + format.parse(params.effectiveDate + " 00:00:00")
    println "date 3: " + new Timestamp(format.parse(params.effectiveDate + " 00:00:00.0").getTime()) + "\n"
    tempLaborInstance.setEffectiveDate(new Date(format.parse(params.effectiveDate + " 00:00:00.0").getTime()))
    tempLaborInstance.setExpiredDate(new Date(format.parse(params.expiredDate + " 00:00:00").getTime()))
    tempLaborInstance.setSignDate(new Date(format.parse(params.signDate + " 00:00:00").getTime()))
    tempLaborInstance.setContractNumber(laborContractInstance.contractNumber)
    tempLaborInstance.setContent(laborContractInstance.content)
    tempLaborInstance.setEmployeeName(laborContractInstance.employeeName)
    tempLaborInstance.setEmployeeDateOfBirth(new Date(format.parse(params.employeeDateOfBirth + " 00:00:00").getTime()))
    tempLaborInstance.setEmployeePhoneNumber(laborContractInstance.employeePhoneNumber)
    tempLaborInstance.setEmployerName(laborContractInstance.employerName)
    tempLaborInstance.setEmployerDateOfBirth(new Date(format.parse(params.employerDateOfBirth + " 00:00:00").getTime()))
    tempLaborInstance.setEmployerPhoneNumber(laborContractInstance.employerPhoneNumber)
    tempLaborInstance.setProfession(laborContractInstance.profession)
    tempLaborInstance.setType(laborContractInstance.type)
    tempLaborInstance.setPhoto(params.photo)
    tempLaborInstance.setFileFolder(params.fileFolder)

    /* ***************************************************
       *              READ COMMAND FIRST                 *
       ***************************************************/
    // ** If the current class has a field as a date attribute, uncommant and reset the code to fix the bug.

//        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd") //set date type
//        userInforInstance.set<date>(dateFormat.format(params.dateOfBirth)); //reset date propertie for this entity
    if (tempLaborInstance.hasErrors()) {
      respond tempLaborInstance.errors, view: 'edit'
      return
    }
    if (LaborContract.findByContractNumberAndIdNotEqual(laborContractInstance.contractNumber, laborContractInstance.id)) {
      flash.message = 'Contract Number is available !'
      flash.message_type = 'error'
      respond laborContractInstance, view: 'edit'
      return
    }
    tempLaborInstance.save flush: true
    laborContractService.saveContractImage(params.image_photo, '');
    laborContractService.saveContractFile(params.attachFile, '');

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.updated.message', args: [message(code: 'LaborContract.label', default: 'LaborContract'), laborContractInstance.id])
        redirect laborContractInstance
      }
      '*' { respond laborContractInstance, [status: OK] }
    }
  }

  @Secured(['ROLE_ADMIN', 'ROLE_MANAGER'])
  @Transactional
  def delete(LaborContract laborContractInstance) {

    if (laborContractInstance == null) {
      notFound()
      return
    }

    def userInformationInstance = UserInfor.findAllByLaborContract(laborContractInstance)
    userInformationInstance.each { UserInfor ->
      UserInfor.delete()
    }

    laborContractInstance.delete flush: true

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.deleted.message', args: [message(code: 'LaborContract.label', default: 'LaborContract'), laborContractInstance.id])
        redirect action: "index", method: "GET"
      }
      '*' { render status: NO_CONTENT }
    }
  }

  protected void notFound() {
    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.not.found.message', args: [message(code: 'laborContract.label', default: 'LaborContract'), params.id])
        redirect action: "index", method: "GET"
      }
      '*' { render status: NOT_FOUND }
    }
  }

  @Secured('permitAll')
  def loadImage() {
    File tempFile = null;
    println("============== Streamming file ==============")
    println('params ========> ' + params)
    response.setContentType("image/**")
    ByteArrayResource resource = assetResourceLocator.findAssetForURI('default.jpg')
    if (params.path) {
      println resource.byteArray
      String path = CommonUtils.IMAGES_PATH + '/' + params.path
      tempFile = new File(path)
      if (tempFile.exists()) {
        response.setHeader("Content-disposition", "filename=${CommonUtils.IMAGES_PATH + '/' + path}")
        response.outputStream << tempFile.newInputStream()
      } else {
        response.outputStream << resource.inputStream
      }
    } else {
      response.outputStream << resource.inputStream
    }

    println("============== End function ==============")
  }

  @Secured('permitAll')
  def uploadImage() {
    response.setContentType("application/json;charset=utf-8")
    println("============== Upload file ==============")
    if (params.path) {
      userInforService.saveUserImage(params.path);
      render createLink(controller: 'userInfor', action: 'loadImage', params: ['image': false, 'path': params.path.originalFilename]);
      println("==============End Upload file ==============")
    }
  }

  @Secured('permitAll')
  def loadFile() {
    File tempFile = null;
    println("============== Streamming file ==============")
    println('params ========> ' + params)

grails-app/views/laborContract/create.gsp
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="adminlte">
  <g:set var="entityName" value="${message(code: 'laborContract.label', default: 'LaborContract')}"/>
  <title><g:message code="default.create.label"
                    args="${[message( code: 'laborContract.label', default:'laborContract')]}">
  </g:message></title>

</head>

<body>
%{--<a href="#create-laborContract" class="skip" tabindex="-1"><g:message code="default.link.skip.label"--}%
%{--                                                                                    default="Skip to content&hellip;"/></a>--}%

%{--<div class="nav" role="navigation">--}%
%{--  <ul>--}%
%{--    <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--}%
%{--    <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>--}%
%{--  </ul>--}%
%{--</div>--}%
<div class="laborContract">
  <div id="create-laborContract" class="content scaffold-create" role="main">
%{--    <h1><g:message code="default.create.label" args="[entityName]"/></h1>--}%
    <g:if test="${flash.message}">
      <div class="message alert alert-${flash.message_type?flash.message_type:'success'}" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${laborContractInstance}">
      <div class="alert alert-warning">
        <ul class="errors" role="alert">
          <g:eachError bean="${laborContractInstance}" var="error">
            <li<g:if
            test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
            error="${error}"/></li>
          </g:eachError>
        </ul>
      </div>
    </g:hasErrors>
    <div class="box box-primary">
      <div class="box-body">

        <g:form class="form rows"
            url="[resource: laborContractInstance, action: 'save']"   enctype="multipart/form-data" >
    <g:render template="form"/>
    <div class="col-md-12"></div>

    <div class="buttons">
      <g:submitButton name="create" class="btn btn-success"
                      value="${message(code: 'default.button.create.label', default: 'Create')}"/>
    </div>
    </g:form>
      </div>

    </div>
</body>
</html>

grails-app/views/laborContract/edit.gsp
<%@ page import="com.hrm.LaborContract" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="adminlte">
  <g:set var="entityName" value="${message(code: 'laborContract.label', default: 'LaborContract')}"/>
  <title>
    <g:message code="default.edit.label"
               args="${[message( code: 'laborContract.label', default:'laborContract')]}">
    </g:message></title>

</head>

<body>
<div class="laborContract">
  <div id="edit-laborContract" class="content scaffold-edit" role="main">
%{--    <h3><g:message code="default.edit.label" args="[entityName]"/></h3>--}%
    <g:if test="${flash.message}">
      <div class="message alert alert-success" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${laborContractInstance}">
      <div class="alert alert-warning">
      <ul>
        <g:eachError bean="${laborContractInstance}" var="error">
          <li><g:message
            error="${error}"/>
          </li>
        </g:eachError>
      </ul>
      </div>
    </g:hasErrors>
    <div class="box box-primary">
      <div class="box-body">
    <g:form class="form rows" url="[resource: laborContractInstance, action: 'update']"
            method="PUT"   enctype="multipart/form-data" >
    <g:hiddenField class="form-control" name="version" value="${laborContractInstance?.version}"/>
    <g:render template="form"/>
    <div class="col-md-12"></div>
    <div class="buttons">
      <g:actionSubmit class="btn btn-success" action="update"
                      value="${message(code: 'default.button.update.label', default: 'Update')}"/>
    </div>
    </g:form>
      </div>
    </div>
  </div>
</div>
</body>
</html>

grails-app/views/laborContract/index.gsp
<%@ page import="com.hrm.LaborContract" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="adminlte">
  <g:set var="entityName" value="${message(code: 'laborContract.label', default: 'LaborContract')}"/>
  <title><g:message code="laborContract.label"
                    args="${[message( code: 'laborContract.label', default:'laborContract')]}">
  </g:message></title>

</head>

<body>
<div class="laborContract">

  <g:if test="${flash.message}">
    <div class="message" role="status">${flash.message}</div>
  </g:if>
  <div id="list-laborContract" class="box box-primary" role="main">
    <div class="box-header">
      <h4 class="box-title collapsed" data-toggle="collapse" data-target="#search-box" aria-expanded="true"><i
        class="fa fa-search"></i><g:message code="default.search.label" args=" "/></h4>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool btn-search-toggle collapsed" data-toggle="collapse"
                data-target="#search-box" aria-expanded="true">
          <i class="fa fa-plus"></i>
        </button>
      </div>
      <div class="help-block"></div>

      <div class="search-laborContract" id="search-box">
          <g:form class="form rows"
                  url="[resource: laborContractInstance, action: 'index']" >
          <g:render template="form"/>
          <div class="buttons col-md-3">
            <label>&nbsp;</label>
            <br>
            <g:submitButton name="search" class="btn btn-success"
                            value="${message(code: 'default.button.search.label', default: 'search')}"/>
          </div>
          </g:form>
        </div>
    </div>
    <div class="box-body">
      <div class="clearfix">
      </div>
      <g:link action="create" class="btn btn-success pull-right"><i class="fa fa-plus"></i></g:link>
      <table class="table table-hover" style="border-top: 1px solid #f4f4f4; border-bottom: 1px solid #f4f4f4">
        <thead>
        <tr>
          <th>#</th>
          
          <g:sortableColumn property="contractNumber"
                            title="${message(code: 'laborContract.contractNumber.label', default: 'Contract Number')}"/>
          
          <g:sortableColumn property="employeeName" style="text-align: left;"
                            title="${message(code: 'laborContract.employeeName.label', default: 'Employee Name')}"/>

          <g:sortableColumn property="employerName" style="text-align: left;"
                            title="${message(code: 'laborContract.employerName.label', default: 'Employer Name')}"/>

          <g:sortableColumn property="professionId"
                            title="${message(code: 'laborContract.professionId.label', default: 'Profession Id')}"/>

          <g:sortableColumn property="typeId"
                            title="${message(code: 'laborContract.typeId.label', default: 'Type Id')}"/>

          <g:sortableColumn property="effectiveDate"
                            title="${message(code: 'laborContract.effectiveDate.label', default: 'Effective Date')}"/>

          <g:sortableColumn property="expiredDate"
                            title="${message(code: 'laborContract.expiredDate.label', default: 'Expired Date')}"/>

          <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <g:each in="${laborContractInstanceList}" status="i" var="laborContractInstance">
          <tr class="${(i % 2) == 0 ? 'even' : 'odd'}" scope="col">
            
            <td>${i+1}</td>

            <td><g:link action="show" id="${laborContractInstance.id}">${fieldValue(bean: laborContractInstance, field: "contractNumber")}</g:link></td>

            <td style="text-align: left" >${fieldValue(bean: laborContractInstance, field: "employeeName")}</td>

            <td style="text-align: left">${fieldValue(bean: laborContractInstance, field: "employerName")}</td>

            <td> ${com.hrm.Profession.findById(fieldValue(bean: laborContractInstance, field: "professionId")).professionName} </td>

            <td>
            ${com.hrm.TypesOfContract.findById(fieldValue(bean: laborContractInstance, field: "typeId")).name}
            </td>

            <td>
              <g:formatDate format="yyyy-MM-dd" date="${laborContractInstance.effectiveDate}"/>
            </td>

            <td>
              <g:formatDate format="yyyy-MM-dd" date="${laborContractInstance.expiredDate}"/>
            </td>

            <td><g:link action="edit" resource="${laborContractInstance}"><i
              class="glyphicon glyphicon-pencil"></i></g:link><g:link class="delete" action="delete"
                                                                      resource="${laborContractInstance}"><i
                class="glyphicon glyphicon-remove"></i></g:link></td>
          </tr>
        </g:each>
        </tbody>
      </table>
    </div>
    <div class="box-footer">
      <div class="pagination sang-pagination">
        <g:paginate total="${laborContractInstanceCount ?: 0}"/>
      </div>
    </div>
  </div>
</div>
</body>
</html>