grails-app/domain/com/hrm/RequestType.groovy
package com.hrm

class RequestType {
    String name
    String description
    static constraints = {
        description blank: true, nullable: true
    }
    static mapping = {
        description sqlType: 'varchar(100)'
    }
}

grails-app/domain/com/hrm/Requests.groovy
package com.hrm

class Requests {
    static belongsTo = [staff:UserInfor,depart:Depart, type:RequestType]
    String status
    Date createdDate = new Date()
    Date acceptedAt
    Date effectedAt
    Date expiredAt
    static constraints = {
        createdDate nullable: true, blank:true
        acceptedAt nullable: true, blank:true
        effectedAt nullable: true, blank:true
        expiredAt nullable: true, blank:true
    }
    static mapping = {
    }
}

grails-app/controllers/com/hrm/RequestsController.groovy
package com.hrm


import grails.plugin.springsecurity.annotation.Secured
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Secured('permitAll')
@Transactional(readOnly = true)
class RequestsController {
  /* ***************************************************
     *              READ COMMAND FIRST                 *
     ***************************************************/
  def requestsService
  static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

  @Secured('permitAll')
  def index(Integer max) {
    params.max = Math.min(max ?: 10, 100)
    def listRequestsInstance
    if (params.search) {
      listRequestsInstance = requestsService.search(params)
    } else {
      listRequestsInstance = Requests.list(params)
    }
    respond listRequestsInstance, model: [requestsInstanceCount: Requests.count(), params: params]
  }

  @Secured(['ROLE_ADMIN','ROLE_MANAGER'])
  def show(Requests requestsInstance) {
    respond requestsInstance
  }

  @Secured('permitAll')
  def create() {
    def requestInstance = new Requests(params)
    if (params.userId) {
      requestInstance.setDepart(Depart.findById(Long.parseLong(params.departId)))
      requestInstance.setStaff(UserInfor.findById(Long.parseLong(params.userId)))
    }
    respond requestInstance
  }

  @Secured('permitAll')
  @Transactional
  def save(Requests requestsInstance) {
    if (requestsInstance == null) {
      notFound()
      return
    }
    Requests tempRequestInstance = requestsService.loadRequestData(params, requestsInstance)
    tempRequestInstance.setStatus('WAITING')
    /* ***************************************************
       *              READ COMMAND FIRST                 *
       ***************************************************/
    // ** If the current class has a field as a date attribute, uncommant and reset the code to fix the bug.

//        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd") //set date type
//        userInforInstance.set<date>(dateFormat.format(params.dateOfBirth)); //reset date propertie for this entity

    if (tempRequestInstance.hasErrors()) {
      respond tempRequestInstance.errors, view: 'create'
      return
    }

    tempRequestInstance.save flush: true

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.created.message', args: [message(code: 'requests.label', default: 'Requests'), tempRequestInstance.id])
        redirect tempRequestInstance
      }
      '*' { respond tempRequestInstance, [status: CREATED] }
    }
  }

  @Secured(['ROLE_ADMIN','ROLE_MANAGER'])
  def edit(Requests requestsInstance) {
    respond requestsInstance
  }

  @Secured('permitAll')
  @Transactional
  def update(Requests requestsInstance) {
    if (requestsInstance == null) {
      notFound()
      return
    }
    Requests tempRequestInstance = requestsService.loadRequestData(params, requestsInstance)
    tempRequestInstance.setStatus('WAITING')
    tempRequestInstance.setId(requestsInstance.id)
    /* ***************************************************
       *              READ COMMAND FIRST                 *
       ***************************************************/
    // ** If the current class has a field as a date attribute, uncommant and reset the code to fix the bug.

//        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd") //set date type
//        userInforInstance.set<date>(dateFormat.format(params.dateOfBirth)); //reset date propertie for this entity
    if (requestsInstance.hasErrors()) {
      respond requestsInstance.errors, view: 'edit'
      return
    }

    requestsInstance.save flush: true

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.updated.message', args: [message(code: 'Requests.label', default: 'Requests'), requestsInstance.id])
        redirect requestsInstance
      }
      '*' { respond requestsInstance, [status: OK] }
    }
  }

  @Secured(['ROLE_ADMIN','ROLE_MANAGER'])
  @Transactional
  def delete(Requests requestsInstance) {

    if (requestsInstance == null) {
      notFound()
      return
    }

    requestsInstance.delete flush: true

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.deleted.message', args: [message(code: 'Requests.label', default: 'Requests'), requestsInstance.id])
        redirect action: "index", method: "GET"
      }
      '*' { render status: NO_CONTENT }
    }
  }

  protected void notFound() {
    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.not.found.message', args: [message(code: 'requests.label', default: 'Requests'), params.id])
        redirect action: "index", method: "GET"
      }
      '*' { render status: NOT_FOUND }
    }
  }

  @Secured(['ROLE_MANAGER', 'ROLE_ADMIN'])
  @Transactional
  def accept() {
    long id = Long.parseLong(params.id);
    Requests requestInstance = Requests.findById(id)
    requestInstance.setStatus('ACCEPTED')
    requestInstance.setAcceptedAt(new Date())
    requestInstance.save(flush: true)
    redirect controller: 'index'
  }

  @Secured(['ROLE_MANAGER', 'ROLE_ADMIN'])
  @Transactional
  def denied() {
    long id = Long.parseLong(params.id);
    def requestInstance = Requests.findById(id)
    requestInstance.setStatus('DENIED')
    requestInstance.save(flush: true)
    redirect controller: 'index'
  }
}

grails-app/views/requests/create.gsp
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="adminlte">
  <g:set var="entityName" value="${message(code: 'requests.label', default: 'Requests')}"/>
  <title><g:message code="default.create.label"
                    args="${[message( code: 'requests.label', default:'requests')]}">
  </g:message></title>

</head>

<body>
%{--<a href="#create-requests" class="skip" tabindex="-1"><g:message code="default.link.skip.label"--}%
%{--                                                                                    default="Skip to content&hellip;"/></a>--}%

%{--<div class="nav" role="navigation">--}%
%{--  <ul>--}%
%{--    <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--}%
%{--    <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>--}%
%{--  </ul>--}%
%{--</div>--}%
<div class="requests">
  <div id="create-requests" class="content scaffold-create" role="main">
%{--    <h1><g:message code="default.create.label" args="[entityName]"/></h1>--}%
    <g:if test="${flash.message}">
      <div class="message alert alert-success" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${requestsInstance}">
      <div class="alert alert-warning">
        <ul class="errors" role="alert">
          <g:eachError bean="${requestsInstance}" var="error">
            <li<g:if
            test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
            error="${error}"/></li>
          </g:eachError>
        </ul>
      </div>
    </g:hasErrors>
    <div class="box box-primary">
      <div class="box-body">

        <g:form class="form rows"
            url="[resource: requestsInstance, action: 'save']" >
    <g:render template="form"/>
    <div class="col-md-12"></div>

    <div class="buttons">
      <g:submitButton name="create" class="btn btn-success"
                      value="${message(code: 'default.button.create.label', default: 'Create')}"/>
    </div>
    </g:form>
      </div>

    </div>
</body>
</html>

grails-app/views/requests/edit.gsp
<%@ page import="com.hrm.Requests" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="adminlte">
  <g:set var="entityName" value="${message(code: 'requests.label', default: 'Requests')}"/>
  <title>
    <g:message code="default.edit.label"
               args="${[message( code: 'requests.label', default:'requests')]}">
    </g:message></title>

</head>

<body>
%{--		<a href="#edit-requests" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>--}%
%{--		<div class="nav" role="navigation">--}%
%{--			<ul>--}%
%{--				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--}%
%{--				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>--}%
%{--				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>--}%
%{--			</ul>--}%
%{--		</div>--}%
<div class="requests">
  <div id="edit-requests" class="content scaffold-edit" role="main">
%{--    <h3><g:message code="default.edit.label" args="[entityName]"/></h3>--}%
    <g:if test="${flash.message}">
      <div class="message alert alert-success" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${requestsInstance}">
      <div class="alert alert-warning">
      <ul class="errors" role="alert">
        <g:eachError bean="${requestsInstance}" var="error">
          <li<g:if
               test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
            error="${error}"/></li>
        </g:eachError>
      </ul>
      </div>
    </g:hasErrors>
    <div class="box box-primary">
      <div class="box-body">
    <g:form class="form rows" url="[resource: requestsInstance, action: 'update']"
            method="PUT" >
    <g:hiddenField class="form-control" name="version" value="${requestsInstance?.version}"/>
    <g:render template="form"/>
    <div class="col-md-12"></div>
    <div class="buttons">
      <g:actionSubmit class="btn btn-success" action="update"
                      value="${message(code: 'default.button.update.label', default: 'Update')}"/>
    </div>
    </g:form>
      </div>
    </div>
  </div>
</div>
</body>
</html>

grails-app/views/requests/index.gsp
<%@ page import="com.hrm.Requests" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="adminlte">
  <g:set var="entityName" value="${message(code: 'requests.label', default: 'Requests')}"/>
  <title><g:message code="requests.label"
                    args="${[message(code: 'requests.label', default: 'requests')]}">
  </g:message></title>

</head>

<body>
<div class="requests">

  <g:if test="${flash.message}">
    <div class="message" role="status">${flash.message}</div>
  </g:if>
  <div id="list-requests" class="box box-primary" role="main">
    <div class="box-header">
      <h4 class="box-title collapsed" data-toggle="collapse" data-target="#search-box" aria-expanded="true"><i
        class="fa fa-search"></i><g:message code="default.search.label" args=" "/></h4>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool btn-search-toggle collapsed" data-toggle="collapse"
                data-target="#search-box" aria-expanded="true">
          <i class="fa fa-plus"></i>
        </button>
      </div>

      <div class="help-block"></div>

      <div class="search-requests " id="search-box">
        <g:form class="form rows"
                url="[resource: requestsInstance, action: 'index']">
          <g:render template="form"/>
          <div class="buttons col-md-4">
            <label>&nbsp;</label>
            <br>

            <g:submitButton name="search" class="btn btn-success"
                            value="${message(code: 'default.button.search.label', default: 'search')}"/>
          </div>
        </g:form>
      </div>
    </div>

    <div class="box-body">
      <div class="clearfix">
      </div>
      <g:link action="create" class="btn btn-success pull-right"><i class="fa fa-plus"></i></g:link>
      <table class="table table-hover" style="border-top: 1px solid #f4f4f4; border-bottom: 1px solid #f4f4f4">
        <thead>
        <tr>
          <th>#</th>
          <th><g:message code="requests.staff.label" default="Staff"/></th>

          <g:sortableColumn property="createdDate"
                            title="${message(code: 'requests.createdDate.label', default: 'Created Date')}"/>

          <g:sortableColumn property="acceptedAt"
                            title="${message(code: 'requests.acceptedAt.label', default: 'Accepted At')}"/>

          <g:sortableColumn property="effectedAt"
                            title="${message(code: 'requests.effectedAt.label', default: 'Effected At')}"/>

          <g:sortableColumn property="expiredAt"
                            title="${message(code: 'requests.expiredAt.label', default: 'Expired At')}"/>


          <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <g:each in="${requestsInstanceList}" status="i" var="requestsInstance">
          <tr class="${(i % 2) == 0 ? 'even' : 'odd'}" scope="col">

            <td>${i+1}</td>

            <td style="text-align: left"><g:link controller="userInfor" action="show"
                        id="${requestsInstance?.staff?.id}">${requestsInstance?.staff?.name}</g:link></td>

            <td><g:formatDate format="yyyy-MM-dd"
                              date="${requestsInstance.createdDate}"/></td>

            <td><g:formatDate format="yyyy-MM-dd"
                              date="${requestsInstance.acceptedAt}"/></td>

            <td><g:formatDate format="yyyy-MM-dd" date="${requestsInstance.effectedAt}"/></td>

            <td><g:formatDate format="yyyy-MM-dd" date="${requestsInstance.expiredAt}"/></td>



            <td><g:link action="edit" resource="${requestsInstance}"><i
              class="glyphicon glyphicon-pencil"></i></g:link><g:link class="delete" action="delete"
                                                                      resource="${requestsInstance}"><i
                class="glyphicon glyphicon-remove"></i></g:link></td>
          </tr>
        </g:each>
        </tbody>
      </table>
    </div>

    <div class="box-footer">
      <div class="pagination sang-pagination">
        <g:paginate total="${requestsInstanceCount ?: 0}"/>
      </div>
    </div>
  </div>
</div>
</body>
</html>

grails-app/views/requests/show.gsp
<%@ page import="com.hrm.Requests" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="adminlte">
  <g:set var="entityName" value="${message(code: 'requests.label', default: 'Requests')}"/>
  <title><g:message code="default.show.label"
                    args="${[message( code: 'requests.label', default:'requests')]}">
</g:message></title>
</head>

<body>
%{--		<a href="#show-requests" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>--}%
%{--		<div class="nav" role="navigation">--}%
%{--			<ul>--}%
%{--				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--}%
%{--				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>--}%
%{--				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>--}%
%{--			</ul>--}%
%{--		</div>--}%
<div class="requests">
  <div id="show-requests" class="content scaffold-show" role="main">
%{--    <h3><g:message code="default.show.label" args="[entityName]"/></h3>--}%
    <g:if test="${flash.message}">
      <div class="message alert alert-success" role="status">${flash.message}</div>
    </g:if>
    <div class="box box-primary">
      <div class="box-body">
        <h4><i class="fa fa-book"></i>Details: </h4>
        <table class="requests table no-margin"s>
          
          %{--          <g:if test="${requestsInstance?.createdDate}">--}%
          <tr class="fieldcontain">
            <th id="createdDate-label" class="property-label"><g:message
              code="requests.createdDate.label" default="Created Date"/></th>
            
            <td class="property-value" aria-labelledby="createdDate-label"><g:formatDate
              format="yyyy-MM-dd"
              date="${requestsInstance?.createdDate}"/></td>
            
          </tr>
          %{--          </g:if>--}%
          
          %{--          <g:if test="${requestsInstance?.acceptedAt}">--}%
          <tr class="fieldcontain">
            <th id="acceptedAt-label" class="property-label"><g:message
              code="requests.acceptedAt.label" default="Accepted At"/></th>
            
            <td class="property-value" aria-labelledby="acceptedAt-label"><g:formatDate
              format="yyyy-MM-dd"
              date="${requestsInstance?.acceptedAt}"/></td>
            
          </tr>
          %{--          </g:if>--}%
          
          %{--          <g:if test="${requestsInstance?.effectedAt}">--}%
          <tr class="fieldcontain">
            <th id="effectedAt-label" class="property-label"><g:message
              code="requests.effectedAt.label" default="Effected At"/></th>
            
            <td class="property-value" aria-labelledby="effectedAt-label"><g:formatDate
              format="yyyy-MM-dd"
              date="${requestsInstance?.effectedAt}"/></td>
            
          </tr>
          %{--          </g:if>--}%
          
          %{--          <g:if test="${requestsInstance?.expiredAt}">--}%
          <tr class="fieldcontain">
            <th id="expiredAt-label" class="property-label"><g:message
              code="requests.expiredAt.label" default="Expired At"/></th>
            
            <td class="property-value" aria-labelledby="expiredAt-label"><g:formatDate
              format="yyyy-MM-dd"
              date="${requestsInstance?.expiredAt}"/></td>
            
          </tr>
          %{--          </g:if>--}%
          
          %{--          <g:if test="${requestsInstance?.depart}">--}%
          <tr class="fieldcontain">
            <th id="depart-label" class="property-label"><g:message
              code="requests.depart.label" default="Depart"/></th>
            
            <td class="property-value" aria-labelledby="depart-label"><g:link
              controller="depart" action="show"
              id="${requestsInstance?.depart?.id}">${requestsInstance?.depart?.name?.encodeAsHTML()}</g:link></td>
            
          </tr>
          %{--          </g:if>--}%
          
          %{--          <g:if test="${requestsInstance?.staff}">--}%
          <tr class="fieldcontain">
            <th id="staff-label" class="property-label"><g:message
              code="requests.staff.label" default="Staff"/></th>
            
            <td class="property-value" aria-labelledby="staff-label"><g:link
              controller="userInfor" action="show"
              id="${requestsInstance?.staff?.id}">${requestsInstance?.staff?.name?.encodeAsHTML()}</g:link></td>
            
          </tr>
          %{--          </g:if>--}%
          
          %{--          <g:if test="${requestsInstance?.status}">--}%
          <tr class="fieldcontain">
            <th id="status-label" class="property-label"><g:message
              code="requests.status.label" default="Status"/></th>
            
            <td class="property-value" aria-labelledby="status-label"><g:fieldValue bean="${requestsInstance}"
                                                                                       field="status"/></td>
            
          </tr>
          %{--          </g:if>--}%
          
          %{--          <g:if test="${requestsInstance?.type}">--}%
          <tr class="fieldcontain">
            <th id="type-label" class="property-label"><g:message
              code="requests.type.label" default="Type"/></th>
            
            <td class="property-value" aria-labelledby="type-label"><g:link
              controller="requestType" action="show"
              id="${requestsInstance?.type?.id}">${requestsInstance?.type?.description?.encodeAsHTML()}</g:link></td>
            
          </tr>
          %{--          </g:if>--}%
          
        </table>
        <g:form url="[resource: requestsInstance, action: 'delete']" method="DELETE">
          <fieldset class="buttons">
            <g:link class="edit btn btn-info" action="edit" resource="${requestsInstance}"><g:message
              code="default.button.edit.label"
              default="Edit"/></g:link>
            <g:actionSubmit class="delete btn btn-danger" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
          </fieldset>
        </g:form>
      </div>
    </div>
  </div>
</div>
</body>
</html>